// GENERATED FILE - DO NOT EDIT
// Generated by: dart run tool/configure_demos.dart
// ignore_for_file: directives_ordering

import '../shared/markdown_demo_widget.dart';

/// List of optional demos that are currently enabled.
/// Configure in optional_demos.yaml and run the configure script.
const List<MarkdownDemoWidget> optionalDemos = <MarkdownDemoWidget>[];
