// ignore_for_file: avoid_print

/// Script to configure optional demos based on optional_demos.yaml
///
/// Usage: dart run tool/configure_demos.dart
///
/// This script reads optional_demos.yaml and:
/// 1. Updates pubspec.yaml with enabled dependencies
/// 2. Generates lib/demos/optional_demos.g.dart with imports and demo list
/// 3. Updates analysis_options.yaml to exclude disabled demo files
library;

import 'dart:io';

import 'package:yaml/yaml.dart';

void main() async {
  final String exampleDir = Directory.current.path.endsWith('example')
      ? Directory.current.path
      : '${Directory.current.path}/example';

  final File configFile = File('$exampleDir/optional_demos.yaml');
  if (!configFile.existsSync()) {
    print('Error: optional_demos.yaml not found');
    exit(1);
  }

  final YamlMap config = loadYaml(configFile.readAsStringSync()) as YamlMap;
  final YamlMap demos = config['demos'] as YamlMap? ?? YamlMap();

  final Map<String, YamlMap> enabledDemos = <String, YamlMap>{};
  final Map<String, YamlMap> disabledDemos = <String, YamlMap>{};

  for (final MapEntry<dynamic, dynamic> entry in demos.entries) {
    final String name = entry.key as String;
    final YamlMap demoConfig = entry.value as YamlMap;
    if (demoConfig['enabled'] == true) {
      enabledDemos[name] = demoConfig;
    } else {
      disabledDemos[name] = demoConfig;
    }
  }

  // 1. Update pubspec.yaml
  await updatePubspec(exampleDir, enabledDemos, disabledDemos);

  // 2. Generate optional_demos.g.dart
  await generateDemoFile(exampleDir, enabledDemos);

  // 3. Update analysis_options.yaml
  await updateAnalysisOptions(exampleDir, disabledDemos);

  print('Configuration complete!');
  print('Enabled demos: ${enabledDemos.keys.join(', ').ifEmpty('none')}');
  print('Disabled demos: ${disabledDemos.keys.join(', ').ifEmpty('none')}');
  print('\nRun "flutter pub get" to update dependencies.');
}

Future<void> updatePubspec(
  String exampleDir,
  Map<String, YamlMap> enabled,
  Map<String, YamlMap> disabled,
) async {
  final File pubspecFile = File('$exampleDir/pubspec.yaml');
  String content = pubspecFile.readAsStringSync();

  // Remove all optional demo dependencies (between markers)
  const String startMarker = '# BEGIN OPTIONAL DEMO DEPENDENCIES';
  const String endMarker = '# END OPTIONAL DEMO DEPENDENCIES';

  final int startIndex = content.indexOf(startMarker);
  final int endIndex = content.indexOf(endMarker);

  if (startIndex != -1 && endIndex != -1) {
    content = content.substring(0, startIndex) + content.substring(endIndex + endMarker.length);
  }

  // Find the dependencies section to insert our optional deps
  final RegExpMatch? dependenciesMatch = RegExp(r'^dependencies:\s*$', multiLine: true).firstMatch(content);
  if (dependenciesMatch == null) {
    print('Error: Could not find dependencies section in pubspec.yaml');
    return;
  }

  // Build the optional dependencies block
  final StringBuffer buffer = StringBuffer();
  buffer.writeln();
  buffer.writeln('  $startMarker');

  for (final MapEntry<String, YamlMap> entry in enabled.entries) {
    final YamlMap config = entry.value;
    final String package = config['package'] as String;
    if (config['path'] != null) {
      buffer.writeln('  $package:');
      buffer.writeln('    path: ${config['path']}');
    } else {
      buffer.writeln('  $package: ${config['version']}');
    }
  }

  // Add disabled ones as comments for reference
  for (final MapEntry<String, YamlMap> entry in disabled.entries) {
    final YamlMap config = entry.value;
    final String package = config['package'] as String;
    buffer.writeln('  # $package: ${config['version']} # disabled');
  }

  buffer.writeln('  $endMarker');

  // Insert after the markdown dependency line (or after dependencies:)
  final RegExpMatch? markdownDepMatch = RegExp(r'^\s+markdown:.*$', multiLine: true).firstMatch(content);
  if (markdownDepMatch != null) {
    final int insertPoint = markdownDepMatch.end;
    content = content.substring(0, insertPoint) + buffer.toString() + content.substring(insertPoint);
  }

  pubspecFile.writeAsStringSync(content);
  print('Updated pubspec.yaml');
}

Future<void> generateDemoFile(String exampleDir, Map<String, YamlMap> enabled) async {
  final StringBuffer buffer = StringBuffer();
  buffer.writeln('// GENERATED FILE - DO NOT EDIT');
  buffer.writeln('// Generated by: dart run tool/configure_demos.dart');
  buffer.writeln('// ignore_for_file: directives_ordering');
  buffer.writeln();

  if (enabled.isEmpty) {
    buffer.writeln("import '../shared/markdown_demo_widget.dart';");
    buffer.writeln();
    buffer.writeln('/// List of optional demos that are currently enabled.');
    buffer.writeln('/// Configure in optional_demos.yaml and run the configure script.');
    buffer.writeln('const List<MarkdownDemoWidget> optionalDemos = <MarkdownDemoWidget>[];');
  } else {
    buffer.writeln("import '../shared/markdown_demo_widget.dart';");

    // Add imports
    for (final MapEntry<String, YamlMap> entry in enabled.entries) {
      final YamlMap config = entry.value;
      buffer.writeln("import '${config['import']}';");

      // Import the demo file (convert lib/demos/x.dart to relative import)
      final String demoFile = (config['demo_file'] as String).replaceFirst('lib/demos/', '');
      buffer.writeln("import '$demoFile';");
    }

    buffer.writeln();
    buffer.writeln('/// List of optional demos that are currently enabled.');
    buffer.writeln('/// Configure in optional_demos.yaml and run the configure script.');
    buffer.writeln('const List<MarkdownDemoWidget> optionalDemos = <MarkdownDemoWidget>[');

    for (final MapEntry<String, YamlMap> entry in enabled.entries) {
      final YamlMap config = entry.value;
      buffer.writeln('  ${config['demo_class']}(),');
    }

    buffer.writeln('];');
  }

  final File outputFile = File('$exampleDir/lib/demos/optional_demos.g.dart');
  outputFile.writeAsStringSync(buffer.toString());
  print('Generated lib/demos/optional_demos.g.dart');
}

Future<void> updateAnalysisOptions(String exampleDir, Map<String, YamlMap> disabled) async {
  final File analysisFile = File('$exampleDir/analysis_options.yaml');

  final StringBuffer buffer = StringBuffer();
  buffer.writeln("# Inherit from the parent package's analysis options");
  buffer.writeln('include: ../analysis_options.yaml');
  buffer.writeln();
  buffer.writeln('analyzer:');
  buffer.writeln('  exclude:');
  buffer.writeln('    # GENERATED - DO NOT EDIT MANUALLY');
  buffer.writeln('    # Run: dart run tool/configure_demos.dart');

  if (disabled.isEmpty) {
    buffer.writeln('    # No demos currently disabled');
  } else {
    for (final MapEntry<String, YamlMap> entry in disabled.entries) {
      final YamlMap config = entry.value;
      buffer.writeln('    - ${config['demo_file']}');
    }
  }

  analysisFile.writeAsStringSync(buffer.toString());
  print('Updated analysis_options.yaml');
}

extension on String {
  String ifEmpty(String fallback) => isEmpty ? fallback : this;
}
